### ISSUE TITLE
Add guidance on how to test when cookies and sessions are enabled

### ISSUE THREAD

**Issue by aeden** [hanami/guides#17]
While reading through the Actions: Sessions section, I miss guidance on how to properly test this. I did find an article that describes using `rack.session` as a param, but it'd be great to have an official way to test in controllers when optional functionality like sessions and cookies are enabled.

**Comment by kaikuchn** [comment]
Hey Anthony,

thanks for raising this issue. If I recall, this or similar questions have been asked in the Chat. So I think you are right, this would be a good thing to add.

Would you like to work on a PR for this?

**Comment by aeden** [comment]
Unfortunately I do not have time to work on a PR for this now.

**Comment by kaikuchn** [comment]
Ok, no worries. I'll put it into my backlog. If you happen to start working on this, just ping use here. If I or somebody else found the time to work on it, we'll do the same.

**Comment by davydovanton** [comment]
@kaikuchn I'll create a PR because I have a lot of experience with testing sessions

**Comment by davydovanton** [comment]
@kaikuchn @aeden could you check my PR?
