### ISSUE TITLE
2.0 to 2.1 upgrade guide

### ISSUE THREAD

**Issue by timriley** [hanami/guides#217]

**Comment by olivierlacan** [comment]
Solid piece to get started on this: https://hanamimastery.com/articles/unofficial-hanami-upgrade-guides

**Comment by timriley** [comment]
Resolved in e475e74.

@olivierlacan — this is just for a 2.0->2.1 upgrade. For 1.x to 2.x, for now we'll have to rely on community resources like the one you linked :)
