### ISSUE TITLE
Understanding code examples in 'custom predicates'

### ISSUE THREAD

**Issue by whysthatso** [hanami/guides#33]
i'm trying to understand the meaning of the last three code blocks at this location:
https://github.com/hanami/guides/blob/master/content/validations/custom-predicates.md#internationalization-i18n

how do they fit into the context of 'custom predicates'?

**Comment by kaikuchn** [comment]
Hey Andreas,

They show case how to create a custom predicate (`uuid?`) with internationalization for the error message when the predicate is violated.
Then how to use that in a reusable parameter validation object and finally how to use that object in a controller.

Does that help you understand what’s going on?

**Comment by kaikuchn** [comment]
Gonna close this, if you have any more questions feel free to reach out again. Either here or in the chat. :)
