### ISSUE TITLE
Broken link on learning how to write ROMRb queries.

### ISSUE THREAD

**Issue by mgiagante** [hanami/guides#44]
I found a broken link at https://guides.hanamirb.org/repositories/overview/
in "Learn more on how to craft queries with ROM and Sequel."
It lead to http://rom-rb.org/current/learn/sql/queries/ which returns 404.
It seems like /current doesn't have a link to that section or at least it doesn't have that shape.

https://rom-rb.org/5.0/learn/sql/queries/ works but it's a specific version (the latest at the moment)

If you agree, I can submit a pull request changing it to that url for the 5.0 version.

Hope it helps.

**Comment by davydovanton** [comment]
hey, thanks for report. Could you make PR with fix?
