### ISSUE TITLE
Left-aligned content looks better then justified

### ISSUE THREAD

**Issue by AndreiEres** [hanami/guides#84]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/27277055/118317367-a5219100-b500-11eb-8058-e0cfa8539959.png">

**Comment by cllns** [comment]
Agreed, I implemented this in PR #82, along with a number of other design tweaks.

**Comment by radar** [comment]
Can this one be closed now?

**Comment by timriley** [comment]
Yep, seems to be resolved by #109.
