### ISSUE TITLE
Text a little hard to read in certain classes with background colors

### ISSUE THREAD

**Issue by ecnal** [hanami/guides#9]
The new Guides are beautiful.  I do have a problem reading text in notice and convention classes.  It's more readable if the font-weight is higher and/or the background color is darker.

**Comment by jodosha** [comment]
@ecnal Could you please send us a screenshot attached in this issue? Thanks.

**Comment by ecnal** [comment]
![screenshot from 2018-10-30 11-32-47](https://user-images.githubusercontent.com/1310070/47730033-adae6680-dc37-11e8-8f1d-54af6c45bd88.png)
![screenshot from 2018-10-30 11-32-24](https://user-images.githubusercontent.com/1310070/47730056-bc951900-dc37-11e8-8238-4cd95218c3b9.png)
![screenshot from 2018-10-30 11-31-24](https://user-images.githubusercontent.com/1310070/47730067-c1f26380-dc37-11e8-9ef2-322e544945f5.png)

**Comment by whysthatso** [comment]
I have the same issue and will provide a pr that might make it a bit more legible.

**Comment by jodosha** [comment]
@ecnal Thanks for closing this. I hope the text is more readable for you now.

**Comment by jodosha** [comment]
Fixed by https://github.com/hanami/guides/pull/30
